### ISSUE TITLE
vcfwave error

### ISSUE THREAD

**Issue by C-YONG** [Han-Cao/collapse-bubble#2]
Thank you very much for the tool you developed. We are using the final MC-generated VCF after clipping（prefix.vcf.gz）, and when we run the code, an error occurs. However, after I modified the code, the error disappeared. Is there any problem?

error：bcftools annotate -x INFO/AT -Ou mc.biallele.uniq_id.vcf.gz | bcftools +fill-tags -- -t AC,AN,AF | vcfwave -I 1000 | bgzip -c > mc.biallele.uniq_id.vcfwave.vcf.gz   

terminate called after throwing an instance of 'std::out_of_range'

The code that runs correctly：bcftools annotate -x INFO/AT -Ou mc.biallele.uniq_id.vcf.gz |  vcfwave -I 1000 | bgzip -c > mc.biallele.uniq_id.vcfwave.vcf.gz

**Comment by Han-Cao** [comment]
Hi,

May I know if your environmental variable `BCFTOOLS_PLUGINS` include the path to BCFtools plugins? You can test this by `bcftools +fill-tags -h` and see if there is an error.

Besides, the reason I added AC,AN,AF annotations in that step was `vcfwave` require this information (not sure if the latest version also requires). So, if you don't have error with `bcftools annotate -x INFO/AT -Ou mc.biallele.uniq_id.vcf.gz | vcfwave -I 1000 | bgzip`, you can just use this.  But it would be always safer to update `AC,AN,AF` before running `collapse_bubble.py`, the script will check these values to determine which SV is the most common one and selected it as the representative for all merged SVs.

**Comment by C-YONG** [comment]
We found that when using fill-tags -- -t AC,AN,AF, all missing samples are changed to AF=. Previously, it was AF=0. Then, when compiling into MNP with AF=., vcfwave encounters an error 
<img width="924" alt="1734519982726" src="https://github.com/user-attachments/assets/67413d3c-9679-4f59-a264-259009ff4c92" />
<img width="923" alt="1734519982733" src="https://github.com/user-attachments/assets/4ace4754-4566-4504-b193-c16a7263a7f2" />
<img width="944" alt="1734519984669" src="https://github.com/user-attachments/assets/fdd0dfc2-70c4-45d3-a95c-b84a7cafc110" />
<img width="942" alt="1734520132377" src="https://github.com/user-attachments/assets/01f69455-fe04-423d-9121-d5e6c8531c13" />

**Comment by C-YONG** [comment]
The last photo is without performing the fill-tags, and it ran successfully.

**Comment by Han-Cao** [comment]
I see, I think `vcfwave` only accept non-missing AF. You can just skip the `+fill-tags` step.

However, I think a pangenome VCF should not include a variant with all missing genotypes, otherwise is it impossible to call the variant. Did you remove any samples from VCF (e.g., remove one reference genome if you include more than 1 ref in MC pipeline)? As `collapse-bubble` check genotypes to reduce false positive SV merging, it would be best to include all samples.

**Comment by C-YONG** [comment]
Thank you for your reply. We didn't remove any samples.The variants with conflict info（for example：CONFLICT=D2_L） in the VCF file generated from our pan-genome are missing. Is this our issue, or is there an issue with the process of constructing our pan-genome?
##INFO=<ID=CONFLICT,Number=.,Type=String,Description="Sample names for which there are multiple paths in the graph with conflicting alle>  
<img width="906" alt="1734524007171" src="https://github.com/user-attachments/assets/4341653c-7157-446b-9b9b-0b9839aeae18" />

**Comment by Han-Cao** [comment]
I was not aware that CONFLICT can cause this when there are not a lot of samples in the pangenome. There is nothing wrong with your data, please just go ahead.

It seems that `bcftools +fill-tags` is not necessary for MC output to run `vcfwave`, I will update the README.

Thanks for sharing this!

**Comment by C-YONG** [comment]
Hello, I have a few more questions. I obtained SVs using a graph-based pan-genome, and additionally, I used vg call to obtain SVs from other second-generation sequencing individuals. The results from vg call contain many lowAD and lowDepth sites. Should I remove them before merging (as I plan to conduct GWAS later)? Should I use vcftools for merging and truvari for collapse, Or simply vcftools merge, or would SURVIVOR be a better option?
Is there any software that can calculate the recall of SVs（pangenome and vg call）?  mabe truvari bench？ When comparing, should I include the pangenome variants that are missing due to conflicts? 
😊I am still a beginner in genomics, thank you for your help.

**Comment by Han-Cao** [comment]
Personally, I never trust the variants called from low depth. Many of those SVs should locate in a difficult region (e.g., repeats) and their genotypes is of low confidence, very likely in many samples. They may make your downstream GWAS quite noisy.

For SV merging, most SVs genotyped by `vg call` should be able to match back to one of the SV in the VCF deconstructed from your pangenome graph. Therefore, I prefer to only do SV merging with the pangenome VCF, and then you can map the SVs genotyped from NGS to this VCF to merge SVs for all samples. This is also why `collapse-bubble.py` output a table to trace how SVs are merged.

However, according to my experience, the output variant of `vg call` can be slightly different from the pangenome VCF, so you can also try other methods to directly merge the population VCF. In the HPRC paper (https://www.nature.com/articles/s41586-023-05896-x), they use `bcftools merge` + `truvari collapse` to do this. I haven't try SURVIVOR before, but it seems SURVIVOR don't consider the insertion sequence when SV merging, so I would suggest not to use SURVIVOR because you already have sequence resolved SVs.

`truvari bench` is widely used to calculate recall. In my own work, I never include missing genotypes in truth set as its genotype is unknown.
